### GET all users
GET http://localhost:3000/users
Accept: application/json

### POST create user 1
POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "Вова"
}

### POST create user 2
POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "Никита",
   "email": "nikita@example.com"
}

### GET user by id 1
GET http://localhost:3000/users/1
Accept: application/json

### GET user not found
GET http://localhost:3000/users/999
Accept: application/json

### POST create user 3
POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "Иван"
}