GET http://localhost:3000/users?auth=true
Accept: application/json

POST http://localhost:3000/users?auth=true
Content-Type: application/json

{
   "name": "Вова"
}

POST http://localhost:3000/users?auth=true
Content-Type: application/json

{
   "name": "Никита",
   "email": "nikita@example.com"
}

GET http://localhost:3000/users/1?auth=true
Accept: application/json

GET http://localhost:3000/users/999?auth=true
Accept: application/json

POST http://localhost:3000/users?auth=true
Content-Type: application/json

{
   "name": "Иван"
}